version: '3.8'
services: 
  postgres:
    container_name: pg-docker
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
    ports:
      - '5432:5432'
    volumes: 
      - '$HOME/docker/volumes/postgres:/var/lib/postgres'
    image: postgres
  
  pgadmin:
    image: 'dpage/pgadmin4:latest'
    container_name: pgadmin
    ports: 
      - '80:80'
    environment: 
      PGADMIN_DEFAULT_EMAIL: pscket@packet.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes: 
      - $HOME/docker/volumes/pgadmin:/var/lib/pgadmin'
# volumes:
#   pgadmin-data:
#   db-data:
